language: common-lisp
sudo: false

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre
env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ecl
    - LISP=abcl
    - LISP=allegro
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=clisp
    - env: LISP=ecl

os:
  - osx
  - linux

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install asdf/3.3.1.1
  - ros install rove
  - ros install 40ants/cl-hamcrest
#  - ros install 40ants/cl-info

before_script:
  - ros --version
  - ros config
#  - cl-info

script:
  - rove defmain-test.asd
