language: common-lisp
sudo: false

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

addons:
  apt:
    packages:
      - libc6-i386

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_BRANCH=master
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin
    - LISP=ecl
    - LISP=abcl
    - LISP=allegro
    - LISP=ccl-bin
    - LISP=clisp
    - LISP=cmucl

matrix:
  allow_failures:
    - env: LISP=cmucl
      # Started to fail at some time.
      # I can't reproduce it in my Docker on OSX, because Allegro does not start on 64bits:
      # /root/.roswell/impls/x86-64/linux/allegro/10.1express/alisp is not executable. Missing 32bit glibc?
    - env: LISP=allegro
      # Turned off, because Rove started fail under CLisp
      # *** - READ from #<INPUT CONCATENATED-STREAM #<INPUT BUFFERED FILE-STREAM CHARACTER #P"/root/.roswell/bin/rove" @116> #<INPUT STRING-INPUT-STREAM>>:
      # #<PACKAGE SYSTEM> has no external symbol with name "SIMPLE-INTERRUPT-CONDITION"
    - env: LISP=clisp

os:
  - osx
  - linux

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh
  - ros install asdf/3.3.1.1
  - ros install rove
  # Using latest dissect because current Quicklisp fails on SBCL 1.4.10
  # https://github.com/fukamachi/qlot/commit/367f87c89b08afca0ff13a8c3b58d0c9fd6cb567
  - ros install Shinmera/dissect
  - ros install 40ants/cl-hamcrest
#  - ros install 40ants/cl-info

before_script:
  - ros --version
  - ros config
#  - cl-info

script:
  - rove defmain-test.asd
